spring.application.name=spring-boot-project
server.servlet.context-path=/api
server.http.port=8080
server.port=8443
server.ssl.enabled=${TINC_GAME_SERVER_HTTPS}
server.ssl.bundle=tincBundle
spring.ssl.bundle.pem.tincBundle.keystore.certificate=file:${TINC_GAME_SERVER_CERT_DIR}/fullchain.pem
spring.ssl.bundle.pem.tincBundle.keystore.private-key=file:${TINC_GAME_SERVER_CERT_DIR}/privkey.pem
