# Basic system
FROM tinc-install-other:latest

# Copy tinc source code
WORKDIR /home/root
COPY Downloads/tinc-1.1pre18.tar.gz /home/root/
RUN tar xvf tinc-1.1pre18.tar.gz
# cd source code dir and build
WORKDIR /home/root/tinc-1.1pre18
RUN ./configure
ARG BUILD_CPU_CORE=1
RUN make -j$BUILD_CPU_CORE
RUN make install
WORKDIR /home/root

# tinc server argument
ENV PMTU_DISCOVERY="yes"
ENV LISTEN_PORT="655"
ENV EXTERNAL_ADDRESS="localhost"
ENV IPV4_SERVER_ADDRESS="10.77.1.1"
ENV IPV4_SUBNET_RANGE_BEGIN="10.77.1.2"
ENV IPV4_SUBNET_RANGE_END="10.77.255.254"
ENV IPV4_SUBNET_PREFIX="16"
ENV IPV4_SUBNET_MASK="255.255.0.0"
ENV DHCP_EXPIRE="12h"
ENV NETWORK_NAME="tinc_docker"
ENV TINC_GAME_SERVER_HTTPS="true"
ENV TINC_GAME_SERVER_CERT_DIR="/home/root"

# Init tinc server
RUN mkdir -p /usr/local/var/run
RUN tinc -n $NETWORK_NAME init server
RUN tinc -n $NETWORK_NAME set Mode switch
# tinc interface script
ENV tincUpScript="/usr/local/etc/tinc/$NETWORK_NAME/tinc-up"

# Copy tinc management tool
COPY Downloads/spring-boot-project-0.0.1-SNAPSHOT.jar /home/root/
# Disabled, you can't truly erase things from docker image after build
# Upload cert with cert receiver at runtime
# COPY Downloads/fullchain.pem /home/root/
# COPY Downloads/privkey.pem /home/root/

# DHCP config, dnsmasq is started by using tinc-up interface up script
ENV dnsmasqConfig="/etc/dnsmasq.conf"

# Make start script
ENV startScript="/home/root/start.sh"
COPY Script/start.sh /home/root/

# Make diagnostic script
ENV diagScript="/home/root/diagnostic.sh"
COPY Script/diagnostic.sh /home/root/

# Start whole system
CMD ["/home/root/start.sh"]
